name: CI

on:
  push:
    branches: ['master']
    paths: ['**/*.rs', 'Cargo.toml']
  pull_request:
    branches: ['master']
    paths: ['**/*.rs', 'Cargo.toml']
  workflow_dispatch:
  schedule:
    # JST 0:00
    - cron: '0 15 * * *'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        env:
          JOBCAN_EMAIL: ${{ secrets.JOBCAN_EMAIL }}
          JOBCAN_PASSWORD: ${{ secrets.JOBCAN_PASSWORD }}
        run: cargo test --verbose
